sudo: false
language: python
python:
  - 3.3
  - 3.4

install: pip install -r requirements.txt
script:
  - flake8 Blocks.pyw
  - flake8 src/constants.py
  - flake8 src/linter.py
  - flake8 src/setup.py
  - flake8 src/utils.py

  - pep257 Blocks.pyw --explain
  - pep257 src/constants.py --explain
  - pep257 src/linter.py --explain
  - pep257 src/setup.py --explain
  - pep257 src/utils.py --explain
