sudo: false
language: python
python:
  - 3.3
  - 3.4

install: pip install -r requirements.txt
script:
  - flake8 Blocks.pyw
  - flake8 constants.py
  - flake8 levelchecks.py
  - flake8 setup.py
  - flake8 utils.py

  - pep257 Blocks.pyw --explain
  - pep257 constants.py --explain
  - pep257 levelchecks.py --explain
  - pep257 setup.py --explain
  - pep257 utils.py --explain
