# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\legendMain.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_legendDiagMain(object):
    def setupUi(self, legendDiagMain):
        legendDiagMain.setObjectName("legendDiagMain")
        legendDiagMain.resize(445, 410)
        legendDiagMain.setMinimumSize(QtCore.QSize(445, 410))
        legendDiagMain.setWindowTitle("Main Blocks Legend - app-name")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui/images/Blocks.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        legendDiagMain.setWindowIcon(icon)
        legendDiagMain.setStyleSheet("QTableWidget {\n"
"    font-size: 9pt;\n"
"    font-family: \"Source Code Pro\", \"Consolas\";\n"
"}")
        self.tableColors = QtWidgets.QTableWidget(legendDiagMain)
        self.tableColors.setGeometry(QtCore.QRect(10, 40, 201, 170))
        self.tableColors.setMinimumSize(QtCore.QSize(201, 170))
        self.tableColors.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableColors.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableColors.setAutoScroll(False)
        self.tableColors.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableColors.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableColors.setObjectName("tableColors")
        self.tableColors.setColumnCount(2)
        self.tableColors.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableColors.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableColors.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableColors.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableColors.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Color")
        self.tableColors.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Code")
        self.tableColors.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Red")
        brush = QtGui.QBrush(QtGui.QColor(232, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableColors.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("R")
        self.tableColors.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Green")
        brush = QtGui.QBrush(QtGui.QColor(19, 194, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableColors.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("G")
        self.tableColors.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Blue")
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableColors.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("B")
        self.tableColors.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Yellow")
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableColors.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Y")
        self.tableColors.setItem(3, 1, item)
        self.tableColors.verticalHeader().setVisible(False)
        self.tableCodes = QtWidgets.QTableWidget(legendDiagMain)
        self.tableCodes.setGeometry(QtCore.QRect(230, 40, 201, 170))
        self.tableCodes.setMinimumSize(QtCore.QSize(201, 170))
        self.tableCodes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCodes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCodes.setAutoScroll(False)
        self.tableCodes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCodes.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableCodes.setObjectName("tableCodes")
        self.tableCodes.setColumnCount(2)
        self.tableCodes.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableCodes.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCodes.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCodes.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCodes.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCodes.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Block Type")
        self.tableCodes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Code")
        self.tableCodes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Tile")
        self.tableCodes.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("T")
        self.tableCodes.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Cube")
        self.tableCodes.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("C")
        self.tableCodes.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Free")
        self.tableCodes.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("F")
        self.tableCodes.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Blocked Wall")
        self.tableCodes.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("BW")
        self.tableCodes.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("West-bound RC")
        self.tableCodes.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("RB")
        self.tableCodes.setItem(4, 1, item)
        self.tableCodes.verticalHeader().setVisible(False)
        self.lbDesc = QtWidgets.QLabel(legendDiagMain)
        self.lbDesc.setGeometry(QtCore.QRect(10, 220, 421, 151))
        self.lbDesc.setMinimumSize(QtCore.QSize(0, 0))
        self.lbDesc.setStyleSheet("font-size: 10pt;\n"
"qproperty-alignment: AlignTop;")
        self.lbDesc.setText("<p><span style=\" font-weight: 700;\">Main Blocks</span> are the primary cubes and tiles used in the levels. Cubes and Tiles are prefixed with a color to create a complete block, e.g., RT creates a Red Tile the player can walk across, and  BC creates a Blue Cube the player can push.</p> <p>Two notable blocks are the Blocked Wall and the West-bound Red Cube. A Blocked Wall is an obstacle the player must navigate around, while the West-bound Red Cube is a a special red cube that can only be pushed to the left side of the board.</p>")
        self.lbDesc.setWordWrap(True)
        self.lbDesc.setObjectName("lbDesc")
        self.lbHeader = QtWidgets.QLabel(legendDiagMain)
        self.lbHeader.setGeometry(QtCore.QRect(150, 10, 131, 21))
        self.lbHeader.setStyleSheet("font-size: 15pt;\n"
"qproperty-alignment: AlignCenter;")
        self.lbHeader.setText("Main Blocks")
        self.lbHeader.setObjectName("lbHeader")
        self.btnClose = QtWidgets.QPushButton(legendDiagMain)
        self.btnClose.setGeometry(QtCore.QRect(180, 370, 75, 23))
        self.btnClose.setText("Close")
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(legendDiagMain)
        self.btnClose.clicked.connect(legendDiagMain.close)
        QtCore.QMetaObject.connectSlotsByName(legendDiagMain)

    def retranslateUi(self, legendDiagMain):
        _translate = QtCore.QCoreApplication.translate
        __sortingEnabled = self.tableColors.isSortingEnabled()
        self.tableColors.setSortingEnabled(False)
        self.tableColors.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.tableCodes.isSortingEnabled()
        self.tableCodes.setSortingEnabled(False)
        self.tableCodes.setSortingEnabled(__sortingEnabled)

import graphics_rc
